// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedmodelsformovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedmodelsformovie));
        
        string IMigrationMetadata.Id
        {
            get { return "201712212156130_updated-models-for-movie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
